package com.googlecode.easyec.modules.bpmn2.dao;

import com.googlecode.easyec.modules.bpmn2.domain.ExtraTaskObject;

import java.util.Map;

public interface ExtraTaskObjectDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BPM_HI_TASK_EXTRA
     *
     * @mbggenerated Sun Aug 24 18:51:59 CST 2014
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BPM_HI_TASK_EXTRA
     *
     * @mbggenerated Sun Aug 24 18:51:59 CST 2014
     */
    int insert(ExtraTaskObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BPM_HI_TASK_EXTRA
     *
     * @mbggenerated Sun Aug 24 18:51:59 CST 2014
     */
    ExtraTaskObject selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BPM_HI_TASK_EXTRA
     *
     * @mbggenerated Sun Aug 24 18:51:59 CST 2014
     */
    int updateByPrimaryKey(ExtraTaskObject record);

    /**
     * 统计已审批的任务列表中的从
     * 最近的一条被拒绝状态的任务
     * 算起，有无指定处理人已审批
     * 过的任务记录的信息。
     *
     * @param params 搜索条件
     * @return 审批过的任务数量
     */
    int countTasksAsReject(Map<String, Object> params);

    /**
     * 统计已审批的任务列表中的
     * 状态为审批通过的任务中，
     * 有无指定处理人已审批过
     * 的任务记录的信息。
     * <p>
     * <b>注意：</b>应该在调用此方法前，
     * 调用{@link #countTasksAsReject(Map)}方法，
     * 以判断流程在运行中有无被拒绝过。
     * </p>
     *
     * @param params 搜索条件
     * @return 审批过的任务数量
     */
    int countTasksAsApprove(Map<String, Object> params);
}